admin:
  contact: eduardo.ragado@hotmail.com
  name: Eduardo Rasgado
  doc:
    title: MediWorld User API Documentation
    description: Mediworld User business API documentation
    version: 1.0.0
    license: Mediworld Ownership
    licenseUrl: #
    termsService: none
app:
  jwtPacienteSecretKey: MediWorld74gcKypJChhzf19fPacienteKey
  jwtMedicoSecretKey: MediWorld74gcKypJChhzf19fMedicoKey
  # 7 dias aproximados de expiracion del token
  jwtExpirationInMs: 604800000
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres?useUnicode=true&useSSL=false&serverTimezone=CDT&useLegacyDatetimeCode=false
    username: postgres
    password: 74gcKypJChhzf19f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          # permite ajustar la zona horaria con la que se guardan fechas en la db
          time_zone: America/Mexico_City
          lob:
            non_contextual_creation: true
  security:
    user:
      name: userapi
      password: mediworlduserapi
  # Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
