admin:
  contact: eduardo.ragado@hotmail.com
  name: Eduardo Rasgado
  doc:
    title: MediWorkd User API Documentation
    description: Mediworld User business API documentation
    version: 1.0.0
    license: Mediworld Ownership
    licenseUrl: #
    termsService: none
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres?useSSL=false&serverTimezone=CDT&useLegacyDatetimeCode=false
    username: postgres
    password: 74gcKypJChhzf19f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: userapi
      password: mediworlduserapi
  # Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: CDT

  queries:
    users-query: SELECT username, password, status FROM usuario WHERE username=?
    roles-query: SELECT username, role FROM role WHERE username =?