spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: 74gcKypJChhzf19f
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  queries:
    users-query: SELECT username, password, status FROM usuario WHERE username=?
    roles-query: SELECT username, role FROM role WHERE username =?